apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        expose: "true"
        app: fraud-detection
      name: fraud-detection
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: fraud-detection
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        version: v1
        expose: "false"
        app: fraud-detection
      name: fraud-detection
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        matchLabels:
          app: fraud-detection
      template:
        metadata:
          labels:
            app: fraud-detection
            version: v1
        spec:
          containers:
            - name: fraud-detection
              image: larchanjo/fraud-detection:0.0.1-SNAPSHOT
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
              livenessProbe:
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 120
              securityContext:
                privileged: false
              - env:
                  - name: KUBERNETES_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: MONGO_HOST
                    value: "mongodb://mongodb.database.svc.cluster.local:27017"
                  - name: NATS_HOST
                    value: "nats://10.43.242.150:4222"
                  - name: NATS_USER
                    value: "nats_client"
                  - name: NATS_PASS
                    value: "DZ3mFLXEDO"
                  - name: JAEGER_ENDPOINT
                    value: "http://jaeger-collector:14268/api/traces"
                  - name: CUSTOMER_SERVICE_HOST
                    value: "customers.payments.svc.cluster.local"
                  - name: CUSTOMER_SERVICE_PORT
                    value: 50051
                  - name: CRM_SERVICE_HOST
                    value: "crm.payments.svc.cluster.local"
                  - name: CRM_PORT
                    value: 8080